macroMapper/
  __init__.py
  main.py
  src/auth/
    Security.py
  src/controller/
    User.py
  src/repository/
    Repository.py
  src/service/
    Service.py
  src/util/
    DBConnect.py
    Middleware.py
    HttpUtils.py
  src/model/
    Result.py
    User.py
    User.py
  tests/
    test_account_repository.py
    test_address_repository.py