macroMapper/
  __init__.py
  main.py
  src/auth/
    Security.py
  src/feature/
    UserAPI.py
  src/model/
    User.py
  src/repository/
    Repository.py
  src/service/
    Service.py
  src/transporters/
    Data.py
    Result.py
  src/util/
    DBConnect.py
    Middleware.py
    HttpUtils.py
    Routes.py
  tests/
    test_repository.py