macroMapper/
  __init__.py
  src/
    main.py
    system/
      auth/
        Security.py
      service/
        Service.py
      repository/
        Repository.py
      transporters/
        Data.py
        Result.py
      util/
        DBConnect.py
        AIConnect.py
        General.py
        Middleware.py
        HttpUtils.py
        Routes.py
    api/
      feature/
        user/
          UserAPI.py
          UserUtils.py
        ai/
          AiAPI.py 
        contract/
          ContractAPI.py
          ContractUtils.py
      model/
        User.py
        Contract.py
  tests/
    test_repository.py